### ISSUE TITLE
Access violation in connection writer

### ISSUE THREAD

**Issue by viciious** [viciious/go-tarantool#24]
Reported with revision 9bf2a85bd5116719981602a060d5799a223ac1c4

```Oct 02 17:13:05 srv.i daemon[5584]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 02 17:13:05 srv.i daemon[5584]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x88058f]
Oct 02 17:13:05 srv.i daemon[5584]: goroutine 601 [running]:
Oct 02 17:13:05 srv.i daemon[5584]: daemon/vendor/github.com/viciious/go-tarantool.(*BinaryPacket).WriteTo(0x0, 0xd044c0, 0xc421985400, 0xe0, 0x0, 0x0)
Oct 02 17:13:05 srv.i daemon[5584]: /root/rpm/BUILD/daemon-f4a656d/_vendor/src/daemon/vendor/github.com/viciious/go-tarantool/binpacket.go:23 +0x2f
Oct 02 17:13:05 srv.i daemon[5584]: daemon/vendor/github.com/viciious/go-tarantool.(*Connection).writer.func1(0xd044c0, 0xc421985400, 0xc4277f3a00, 0x0, 0x0)
Oct 02 17:13:05 srv.i daemon[5584]: /root/rpm/BUILD/daemon-f4a656d/_vendor/src/daemon/vendor/github.com/viciious/go-tarantool/connection.go:478 +0x87
Oct 02 17:13:05 srv.i daemon[5584]: daemon/vendor/github.com/viciious/go-tarantool.(*Connection).writer(0xc42192a1c0, 0x45c2e6, 0xd0b1c0)
Oct 02 17:13:05 srv.i daemon[5584]: /root/rpm/BUILD/daemon-f4a656d/_vendor/src/daemon/vendor/github.com/viciious/go-tarantool/connection.go:507 +0x371
Oct 02 17:13:05 srv.i daemon[5584]: daemon/vendor/github.com/viciious/go-tarantool.(*Connection).worker.func1(0xc42192a1c0, 0xc4201b9ff0)
Oct 02 17:13:05 srv.i daemon[5584]: /root/rpm/BUILD/daemon-f4a656d/_vendor/src/daemon/vendor/github.com/viciious/go-tarantool/connection.go:415 +0x2b
Oct 02 17:13:05 srv.i daemon[5584]: created by daemon/vendor/github.com/viciious/go-tarantool.(*Connection).worker
Oct 02 17:13:05 srv.i daemon[5584]: /root/rpm/BUILD/daemon-f4a656d/_vendor/src/daemon/vendor/github.com/viciious/go-tarantool/connection.go:414 +0x79
```

**Comment by viciious** [comment]
Fixed in e53845410a6aa33e79c3f0420a2a2984bedc493f
